//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question_Paper_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public int ApprovalID { get; set; }
        public int QuestionPaperID { get; set; }
        public int ApproverID { get; set; }
        public string ApprovalStatus { get; set; }
        public System.DateTime ApprovalTimestamp { get; set; }
    
        public virtual User User { get; set; }
        public virtual QuestionPaper QuestionPaper { get; set; }
    }
}
