//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question_Paper_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionID { get; set; }
        public string Role { get; set; }
        public bool CanCreateQuestionPaper { get; set; }
        public bool CanEditQuestionPaper { get; set; }
        public bool CanDeleteQuestionPaper { get; set; }
        public bool CanReviewQuestionPaper { get; set; }
    }
}
